CR-1258 | improving logging in rest handler
ONSdigital/census-int-common-service pull request #52
Opened 2020-10-28 09:55 UTC by akritisinhaa

Updated the logging within the RestExceptionHandler

2020-10-28 10:31 UTC, rpcatling requested changes
These are not the changes I expected. I thought we discussed removing the stack trace from anything that was not level ERROR.

2020-10-28 11:41 UTC, akritisinhaa commented
@rpcatling Changes made as requested. Please check this is what you expected. Also I have left the changes I made before because I felt there should be better logging message than just saying "Handling CTPException"

2020-10-29 08:20 UTC, rpcatling requested changes
Made some minor comments on the wording.
In addition can we please look at all the Logging error() method calls and ensure a stack trace is generated with the causing exception. 

Note that godaddy logging also adds extra form of the error method that allows the exception to be the first parameter. 
```
 void error(Throwable t, String format, Object... args);
```
This is helpful if we want vararg parameters at the end.

2020-10-29 08:20 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
> +            .warn("Handling CTPException - The resource looking for is not found");
English could be better, suggest:
```
Handling CTPException - The resource was not found
```

2020-10-29 08:20 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
> +            .warn("Handling CTPException - The request is accepted  but unable to process");
picky, but remove extra space before 'but'

2020-10-29 08:20 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
> +            .error("Handling CTPException - System error has taken place", exception);
The words 'has taken place' are unnecessary.

2020-10-29 10:42 UTC, rpcatling approved these changes

2020-10-29 10:59 UTC, akritisinhaa commented
LGTM

2020-10-29 11:00 UTC, devenrawat reviewed
one minor

2020-10-29 11:00 UTC, devenrawat commented on src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
> +            .warn("Handling CTPException - The resource was not found");
Message could be "Resource not found"

2020-10-29 11:06 UTC, akritisinhaa commented on src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
> +            .warn("Handling CTPException - The resource was not found");
done

2020-10-29 11:14 UTC, devenrawat approved these changes

2020-10-29 11:18 UTC, merged