CR-1267 | updating logging for monitoring
ONSdigital/census-int-common-service pull request #55
Opened 2020-12-08 16:08 UTC by akritisinhaa

2020-12-08 16:46 UTC, rpcatling approved these changes
Just minor updates.

2020-12-08 16:46 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/common/cloud/FirestoreDataStore.java
> +    log.with(schema).with(key).info("Saving object to Firestore");
probably best to have named items here 
```
log.with("schema", schema).with("key", key).info( ....);
```

2020-12-08 16:46 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/common/cloud/FirestoreDataStore.java
> +      log.with(schema).with(key).info("Firestore save completed");
probably best to have named items here 
```
log.with("schema", schema).with("key", key).info( ....);
```

2020-12-08 22:27 UTC, akritisinhaa commented on src/main/java/uk/gov/ons/ctp/common/cloud/FirestoreDataStore.java
> +    log.with(schema).with(key).info("Saving object to Firestore");
done

2020-12-08 22:28 UTC, akritisinhaa commented on src/main/java/uk/gov/ons/ctp/common/cloud/FirestoreDataStore.java
> +      log.with(schema).with(key).info("Firestore save completed");
done

2020-12-09 12:01 UTC, cookel2 requested changes
please see comment - just one small change suggested

2020-12-09 12:01 UTC, cookel2 commented on src/main/java/uk/gov/ons/ctp/common/cloud/FirestoreDataStore.java
> +      log.with("schema", schema).with("key", schema).info("Firestore save completed");
I think this says schema where it should say key. I suggest this:
```suggestion
      log.with("schema", schema).with("key", key).info("Firestore save completed");
```

2020-12-09 13:04 UTC, cookel2 approved these changes
looks good and builds successfully in travis now

2020-12-09 13:28 UTC, merged